version: "2"
run:
  go: "1.24"
linters:
  enable:
    - staticcheck
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    staticcheck:
      checks:
        - -QF1003
severity:
  default: error
formatters:
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/sbchaos/query
